import Migration, { MigrationFunction } from 'contentful-migration'

// Generated by contentful-schema-diff
// from i1ay3ni34n6m
// to   sd0i1a7mk386
export = function(migration: Migration, { makeRequest, spaceId, accessToken }) {
    /************  blogPost  ******************/

    var blogpost = migration.createContentType('blogPost', {
        displayField: 'title',
        name: 'Blog Post from model',
        description: 'model as code',
    })

    blogpost.createField('title', {
        name: 'Title',
        type: 'Text',
        localized: false,
        required: true,
        validations: [],
        disabled: false,
        omitted: false,
    })

    blogpost.changeFieldControl('title', 'builtin', 'undefined')

    /************  linkPreview  ******************/

    var linkpreview = migration.createContentType('linkPreview', {
        displayField: 'url',
        name: 'Link Preview',
        description: '',
    })

    linkpreview.createField('url', {
        name: 'Url',
        type: 'Symbol',
        localized: false,
        required: false,
        validations: [
            {
                regexp: {
                    pattern:
                        '^(ftp|http|https):\\/\\/(\\w+:{0,1}\\w*@)?(\\S+)(:[0-9]+)?(\\/|\\/([\\w#!:.?+=&%@!\\-\\/]))?$',
                },
            },
        ],
        disabled: false,
        omitted: false,
    })

    linkpreview.changeFieldControl('url', 'builtin', 'urlEditor')

    /************  post  ******************/

    var post = migration.createContentType('post', {
        displayField: 'title',
        name: 'Post',
        description: '',
    })

    post.createField('title', {
        name: 'Title',
        type: 'Symbol',
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
    })

    post.createField('body', {
        name: 'Body',
        type: 'RichText',
        localized: false,
        required: false,
        validations: [
            {
                nodes: {
                    'embedded-entry-block': [{ linkContentType: ['imageGallery', 'linkPreview'] }],
                },
            },
            {
                enabledNodeTypes: [
                    'heading-1',
                    'heading-2',
                    'heading-3',
                    'heading-4',
                    'heading-5',
                    'heading-6',
                    'ordered-list',
                    'unordered-list',
                    'hr',
                    'blockquote',
                    'embedded-entry-block',
                    'embedded-asset-block',
                    'hyperlink',
                    'entry-hyperlink',
                    'asset-hyperlink',
                ],
                message:
                    'Only heading 1, heading 2, heading 3, heading 4, heading 5, heading 6, ordered list, unordered list, horizontal rule, quote, block entry, asset, link to Url, link to entry, and link to asset nodes are allowed',
            },
        ],
        disabled: false,
        omitted: false,
    })

    post.changeFieldControl('title', 'builtin', 'singleLine')

    post.changeFieldControl('body', 'builtin', 'richTextEditor')

    /************  imageGallery  ******************/

    var imagegallery = migration.createContentType('imageGallery', {
        displayField: 'title',
        name: 'Image Gallery',
        description: '',
    })

    imagegallery.createField('title', {
        name: 'Title',
        type: 'Symbol',
        localized: false,
        required: false,
        validations: [],
        disabled: false,
        omitted: false,
    })

    imagegallery.createField('image1', {
        name: 'Image 1',
        type: 'Link',
        localized: false,
        required: true,
        validations: [{ linkMimetypeGroup: ['image'] }],
        disabled: false,
        omitted: false,
        linkType: 'Asset',
    })

    imagegallery.createField('image2', {
        name: 'Image 2',
        type: 'Link',
        localized: false,
        required: false,
        validations: [{ linkMimetypeGroup: ['image'] }],
        disabled: false,
        omitted: false,
        linkType: 'Asset',
    })

    imagegallery.createField('image3', {
        name: 'Image 3',
        type: 'Link',
        localized: false,
        required: false,
        validations: [{ linkMimetypeGroup: ['image'] }],
        disabled: false,
        omitted: false,
        linkType: 'Asset',
    })

    imagegallery.createField('image4', {
        name: 'Image 4',
        type: 'Link',
        localized: false,
        required: false,
        validations: [{ linkMimetypeGroup: ['image'] }],
        disabled: false,
        omitted: false,
        linkType: 'Asset',
    })

    imagegallery.changeFieldControl('title', 'builtin', 'singleLine')

    imagegallery.changeFieldControl('image1', 'builtin', 'assetLinkEditor')

    imagegallery.changeFieldControl('image2', 'builtin', 'assetLinkEditor')

    imagegallery.changeFieldControl('image3', 'builtin', 'assetLinkEditor')

    imagegallery.changeFieldControl('image4', 'builtin', 'assetLinkEditor')
} as MigrationFunction
