export const NEWS = '/'
export const ARTISTS = '/artists'
export const RELEASES = '/releases'
export const PODCASTS = '/podcasts'
export const EVENTS = '/events'
export const CONTACT = '/contact'
export const ACCOUNT = '/account'
